version: '3'
services:
  habit-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/HabitTracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root 

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: HabitTracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    # volumes:
    #   - pgdata:/var/lib/postgresql/data


 



volumes:
  pgdata:
  # esdata:
