package com.bnt.constant.enums;

// public enum Day {
//     EVERYDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY, 
//     ONCE, TWICE, THRICE, FOURTH,
//     JANUARY, FEBRUARY, MARCH, APRIL, MAY, JUNE, JULY, AUGUST, SEPTEMBER, OCTOBER, NOVEMBER, DECEMBER
// }

public enum Day {
    ONCE, TWICE, THRICE, FOURTH
}


